CREATE TABLE IF NOT EXISTS user_showcase_inventory (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    card_id VARCHAR(50) NOT NULL,
    is_foil BOOLEAN DEFAULT FALSE,
    acquired_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_showcase_inventory_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS packs INT DEFAULT 0;
