// Autogenerated offline fallback database for XY1 cards
export interface LocalCardMetadata {
  id: string;
  name: string;
  supertype: string;
  subtypes: string[];
}

export const LOCAL_CARDS_DB: Record<string, LocalCardMetadata> = {
  "xy1-1": {
    "id": "xy1-1",
    "name": "Venusaur-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic",
      "EX"
    ]
  },
  "xy1-2": {
    "id": "xy1-2",
    "name": "M Venusaur-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "MEGA",
      "EX"
    ]
  },
  "xy1-3": {
    "id": "xy1-3",
    "name": "Weedle",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-4": {
    "id": "xy1-4",
    "name": "Kakuna",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-5": {
    "id": "xy1-5",
    "name": "Beedrill",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-6": {
    "id": "xy1-6",
    "name": "Ledyba",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-7": {
    "id": "xy1-7",
    "name": "Ledian",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-8": {
    "id": "xy1-8",
    "name": "Volbeat",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-9": {
    "id": "xy1-9",
    "name": "Illumise",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-10": {
    "id": "xy1-10",
    "name": "Pansage",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-11": {
    "id": "xy1-11",
    "name": "Simisage",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-12": {
    "id": "xy1-12",
    "name": "Chespin",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-13": {
    "id": "xy1-13",
    "name": "Quilladin",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-14": {
    "id": "xy1-14",
    "name": "Chesnaught",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-15": {
    "id": "xy1-15",
    "name": "Scatterbug",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-16": {
    "id": "xy1-16",
    "name": "Spewpa",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-17": {
    "id": "xy1-17",
    "name": "Vivillon",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-18": {
    "id": "xy1-18",
    "name": "Skiddo",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-19": {
    "id": "xy1-19",
    "name": "Gogoat",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-20": {
    "id": "xy1-20",
    "name": "Slugma",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-21": {
    "id": "xy1-21",
    "name": "Magcargo",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-22": {
    "id": "xy1-22",
    "name": "Pansear",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-23": {
    "id": "xy1-23",
    "name": "Simisear",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-24": {
    "id": "xy1-24",
    "name": "Fennekin",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-25": {
    "id": "xy1-25",
    "name": "Braixen",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-26": {
    "id": "xy1-26",
    "name": "Delphox",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-27": {
    "id": "xy1-27",
    "name": "Fletchinder",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-28": {
    "id": "xy1-28",
    "name": "Talonflame",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-29": {
    "id": "xy1-29",
    "name": "Blastoise-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic",
      "EX"
    ]
  },
  "xy1-30": {
    "id": "xy1-30",
    "name": "M Blastoise-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "MEGA",
      "EX"
    ]
  },
  "xy1-31": {
    "id": "xy1-31",
    "name": "Shellder",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-32": {
    "id": "xy1-32",
    "name": "Cloyster",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-33": {
    "id": "xy1-33",
    "name": "Staryu",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-34": {
    "id": "xy1-34",
    "name": "Starmie",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-35": {
    "id": "xy1-35",
    "name": "Lapras",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-36": {
    "id": "xy1-36",
    "name": "Corsola",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-37": {
    "id": "xy1-37",
    "name": "Panpour",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-38": {
    "id": "xy1-38",
    "name": "Simipour",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-39": {
    "id": "xy1-39",
    "name": "Froakie",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-40": {
    "id": "xy1-40",
    "name": "Frogadier",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-41": {
    "id": "xy1-41",
    "name": "Greninja",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-42": {
    "id": "xy1-42",
    "name": "Pikachu",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-43": {
    "id": "xy1-43",
    "name": "Raichu",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-44": {
    "id": "xy1-44",
    "name": "Voltorb",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-45": {
    "id": "xy1-45",
    "name": "Electrode",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-46": {
    "id": "xy1-46",
    "name": "Emolga-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic",
      "EX"
    ]
  },
  "xy1-47": {
    "id": "xy1-47",
    "name": "Ekans",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-48": {
    "id": "xy1-48",
    "name": "Arbok",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-49": {
    "id": "xy1-49",
    "name": "Spoink",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-50": {
    "id": "xy1-50",
    "name": "Grumpig",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-51": {
    "id": "xy1-51",
    "name": "Venipede",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-52": {
    "id": "xy1-52",
    "name": "Whirlipede",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-53": {
    "id": "xy1-53",
    "name": "Scolipede",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-54": {
    "id": "xy1-54",
    "name": "Phantump",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-55": {
    "id": "xy1-55",
    "name": "Trevenant",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-56": {
    "id": "xy1-56",
    "name": "Pumpkaboo",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-57": {
    "id": "xy1-57",
    "name": "Gourgeist",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-58": {
    "id": "xy1-58",
    "name": "Diglett",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-59": {
    "id": "xy1-59",
    "name": "Dugtrio",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-60": {
    "id": "xy1-60",
    "name": "Rhyhorn",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-61": {
    "id": "xy1-61",
    "name": "Rhydon",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-62": {
    "id": "xy1-62",
    "name": "Rhyperior",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-63": {
    "id": "xy1-63",
    "name": "Lunatone",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-64": {
    "id": "xy1-64",
    "name": "Solrock",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-65": {
    "id": "xy1-65",
    "name": "Timburr",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-66": {
    "id": "xy1-66",
    "name": "Gurdurr",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-67": {
    "id": "xy1-67",
    "name": "Conkeldurr",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-68": {
    "id": "xy1-68",
    "name": "Sableye",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-69": {
    "id": "xy1-69",
    "name": "Sandile",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-70": {
    "id": "xy1-70",
    "name": "Krokorok",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-71": {
    "id": "xy1-71",
    "name": "Krookodile",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-72": {
    "id": "xy1-72",
    "name": "Zorua",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-73": {
    "id": "xy1-73",
    "name": "Zoroark",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-74": {
    "id": "xy1-74",
    "name": "Inkay",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-75": {
    "id": "xy1-75",
    "name": "Inkay",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-76": {
    "id": "xy1-76",
    "name": "Malamar",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-77": {
    "id": "xy1-77",
    "name": "Malamar",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-78": {
    "id": "xy1-78",
    "name": "Yveltal",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-79": {
    "id": "xy1-79",
    "name": "Yveltal-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic",
      "EX"
    ]
  },
  "xy1-80": {
    "id": "xy1-80",
    "name": "Skarmory-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic",
      "EX"
    ]
  },
  "xy1-81": {
    "id": "xy1-81",
    "name": "Pawniard",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-82": {
    "id": "xy1-82",
    "name": "Bisharp",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-83": {
    "id": "xy1-83",
    "name": "Honedge",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-84": {
    "id": "xy1-84",
    "name": "Doublade",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-85": {
    "id": "xy1-85",
    "name": "Aegislash",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-86": {
    "id": "xy1-86",
    "name": "Aegislash",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-87": {
    "id": "xy1-87",
    "name": "Jigglypuff",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-88": {
    "id": "xy1-88",
    "name": "Jigglypuff",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-89": {
    "id": "xy1-89",
    "name": "Wigglytuff",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-90": {
    "id": "xy1-90",
    "name": "Wigglytuff",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-91": {
    "id": "xy1-91",
    "name": "Mr. Mime",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-92": {
    "id": "xy1-92",
    "name": "Spritzee",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-93": {
    "id": "xy1-93",
    "name": "Aromatisse",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-94": {
    "id": "xy1-94",
    "name": "Swirlix",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-95": {
    "id": "xy1-95",
    "name": "Slurpuff",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-96": {
    "id": "xy1-96",
    "name": "Xerneas",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-97": {
    "id": "xy1-97",
    "name": "Xerneas-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic",
      "EX"
    ]
  },
  "xy1-98": {
    "id": "xy1-98",
    "name": "Doduo",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-99": {
    "id": "xy1-99",
    "name": "Dodrio",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-100": {
    "id": "xy1-100",
    "name": "Tauros",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-101": {
    "id": "xy1-101",
    "name": "Dunsparce",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-102": {
    "id": "xy1-102",
    "name": "Taillow",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-103": {
    "id": "xy1-103",
    "name": "Swellow",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-104": {
    "id": "xy1-104",
    "name": "Skitty",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-105": {
    "id": "xy1-105",
    "name": "Delcatty",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-106": {
    "id": "xy1-106",
    "name": "Bidoof",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-107": {
    "id": "xy1-107",
    "name": "Bibarel",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-108": {
    "id": "xy1-108",
    "name": "Lillipup",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-109": {
    "id": "xy1-109",
    "name": "Herdier",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-110": {
    "id": "xy1-110",
    "name": "Stoutland",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 2"
    ]
  },
  "xy1-111": {
    "id": "xy1-111",
    "name": "Bunnelby",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-112": {
    "id": "xy1-112",
    "name": "Diggersby",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ]
  },
  "xy1-113": {
    "id": "xy1-113",
    "name": "Fletchling",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-114": {
    "id": "xy1-114",
    "name": "Furfrou",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-115": {
    "id": "xy1-115",
    "name": "Cassius",
    "supertype": "Trainer",
    "subtypes": [
      "Supporter"
    ]
  },
  "xy1-116": {
    "id": "xy1-116",
    "name": "Evosoda",
    "supertype": "Trainer",
    "subtypes": [
      "Item"
    ]
  },
  "xy1-117": {
    "id": "xy1-117",
    "name": "Fairy Garden",
    "supertype": "Trainer",
    "subtypes": [
      "Stadium"
    ]
  },
  "xy1-118": {
    "id": "xy1-118",
    "name": "Great Ball",
    "supertype": "Trainer",
    "subtypes": [
      "Item"
    ]
  },
  "xy1-119": {
    "id": "xy1-119",
    "name": "Hard Charm",
    "supertype": "Trainer",
    "subtypes": [
      "Pokémon Tool"
    ]
  },
  "xy1-120": {
    "id": "xy1-120",
    "name": "Max Revive",
    "supertype": "Trainer",
    "subtypes": [
      "Item"
    ]
  },
  "xy1-121": {
    "id": "xy1-121",
    "name": "Muscle Band",
    "supertype": "Trainer",
    "subtypes": [
      "Pokémon Tool"
    ]
  },
  "xy1-122": {
    "id": "xy1-122",
    "name": "Professor Sycamore",
    "supertype": "Trainer",
    "subtypes": [
      "Supporter"
    ]
  },
  "xy1-124": {
    "id": "xy1-124",
    "name": "Red Card",
    "supertype": "Trainer",
    "subtypes": [
      "Item"
    ]
  },
  "xy1-125": {
    "id": "xy1-125",
    "name": "Roller Skates",
    "supertype": "Trainer",
    "subtypes": [
      "Item"
    ]
  },
  "xy1-126": {
    "id": "xy1-126",
    "name": "Shadow Circle",
    "supertype": "Trainer",
    "subtypes": [
      "Stadium"
    ]
  },
  "xy1-127": {
    "id": "xy1-127",
    "name": "Shauna",
    "supertype": "Trainer",
    "subtypes": [
      "Supporter"
    ]
  },
  "xy1-128": {
    "id": "xy1-128",
    "name": "Super Potion",
    "supertype": "Trainer",
    "subtypes": [
      "Item"
    ]
  },
  "xy1-129": {
    "id": "xy1-129",
    "name": "Team Flare Grunt",
    "supertype": "Trainer",
    "subtypes": [
      "Supporter"
    ]
  },
  "xy1-130": {
    "id": "xy1-130",
    "name": "Double Colorless Energy",
    "supertype": "Energy",
    "subtypes": [
      "Special"
    ]
  },
  "xy1-131": {
    "id": "xy1-131",
    "name": "Rainbow Energy",
    "supertype": "Energy",
    "subtypes": [
      "Special"
    ]
  },
  "xy1-132": {
    "id": "xy1-132",
    "name": "Grass Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-133": {
    "id": "xy1-133",
    "name": "Fire Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-134": {
    "id": "xy1-134",
    "name": "Water Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-135": {
    "id": "xy1-135",
    "name": "Lightning Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-136": {
    "id": "xy1-136",
    "name": "Psychic Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-137": {
    "id": "xy1-137",
    "name": "Fighting Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-138": {
    "id": "xy1-138",
    "name": "Darkness Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-139": {
    "id": "xy1-139",
    "name": "Metal Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-140": {
    "id": "xy1-140",
    "name": "Fairy Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ]
  },
  "xy1-141": {
    "id": "xy1-141",
    "name": "Venusaur-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic",
      "EX"
    ]
  },
  "xy1-142": {
    "id": "xy1-142",
    "name": "Blastoise-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic",
      "EX"
    ]
  },
  "xy1-143": {
    "id": "xy1-143",
    "name": "Emolga-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic",
      "EX"
    ]
  },
  "xy1-144": {
    "id": "xy1-144",
    "name": "Yveltal-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic",
      "EX"
    ]
  },
  "xy1-145": {
    "id": "xy1-145",
    "name": "Skarmory-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic",
      "EX"
    ]
  },
  "xy1-146": {
    "id": "xy1-146",
    "name": "Xerneas-EX",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic",
      "EX"
    ]
  }
};
